### ISSUE TITLE
libdrizzle, libdrizzle-dev and libdrizzle-dbg package versions should match

### ISSUE THREAD

**Issue by mathias-lang-sociomantic** [sociomantic/libdrizzle-redux#149]
I mistakenly installed `libdrizzle-redux-dev=5.6.0-xenial` without installing `libdrizzle-redux=5.6.0-xenial`.
Docker output:

```
Selecting previously unselected package libdrizzle-redux.
Preparing to unpack .../libdrizzle-redux_6.0.0-xenial_all.deb ...
Unpacking libdrizzle-redux (6.0.0-xenial) ...
Selecting previously unselected package libdrizzle-redux-dev.
Preparing to unpack .../libdrizzle-redux-dev_5.6.0-xenial_all.deb ...
Unpacking libdrizzle-redux-dev (5.6.0-xenial) ...
```

That shouldn't be possible. One of the way to do so would be to change the package name with a new major.

**Comment by andreas-bok-sociomantic** [comment]
I see, can we do this with a minor release on v6 or will it require a new major version?

**Comment by mathias-lang-sociomantic** [comment]
I'd say a packaging fix won't after the ABI so we can do it in a minor. @ben-palmer-sociomantic ?

**Comment by ben-palmer-sociomantic** [comment]
I'm not too up with packaging issues but if it won't alter the ABI it should be fine to do it in a minor I reckon.

**Comment by andreas-bok-sociomantic** [comment]
I have created a PR #150 to address the issue. 
I am in doubt about at what stage the major version should be added, though.  @leandro-lucarella-sociomantic 

- in `configure.ac` meaning that the exported autoconf vars **PACKAGE** and **PACKAGE_NAME** will be eg. `libdrizzle-redux-6`
- when building the packages, ie.  in the `deb/build` script so the deb package is renamed from `libdrizzle-redux-6` and the .so file to `libdrizzle-redux-6.so`
- should the directory for include headers when installed contain the major version suffix, e.g. `/usr/lib/include/libdrizzle-redux-6`

Technical and spiritual guidance are appreciated.

**Comment by leandro-lucarella-sociomantic** [comment]
Should be a patch-level release if it's only a packaging change.

**Comment by leandro-lucarella-sociomantic** [comment]
> I am in doubt about at what stage the major version should be added, though.

I'm not entirely sure either but I think adding the version to the file is mostly a debian packaging artefact, since it's the way to support installing multiple versions concurrently (actually I'm not even sure if that's necessary if the soname is properly set). I don't think the headers should include it, for that it might be better to install headers in a different directory, i.e.: `/usr/include/libdrizzle-redux/libdrizzle-redux6/libdrizzle-redux` so then an application could use `-I/usr/include/libdrizzle-redux/libdrizzle-redux6` and then `#include <libdrizzle-redux/whatever.h>` to use this version).

> Technical and spiritual guidance are appreciated.

I don't know if the technical guidance was useful, but for spiritual guidance you have to reach the [Kwik E Mart President and CEO](https://www.youtube.com/watch?v=Qf3xwmXXDH8) and use your 3 questions wisely.

**Comment by andreas-bok-sociomantic** [comment]
> I don't know if the technical guidance was useful, but for spiritual guidance you have to reach the Kwik E Mart President and CEO and use your 3 questions wisely.

Really? :)
